// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1onqLAqWIvqAHghnj-bVY_tRYH8IVQfs',
    appId: '1:1027147869074:web:a33a76bf19709e14b1af4b',
    messagingSenderId: '1027147869074',
    projectId: 'nelson-c2230',
    authDomain: 'nelson-c2230.firebaseapp.com',
    storageBucket: 'nelson-c2230.appspot.com',
    measurementId: 'G-X2HB2JCPX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChAVm_wadzbNhJ7lG1kb99eeeQ_AG6iAg',
    appId: '1:1027147869074:android:d639eb586c83387eb1af4b',
    messagingSenderId: '1027147869074',
    projectId: 'nelson-c2230',
    storageBucket: 'nelson-c2230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5LfP_5RsYigfO9IxfGjQaO252X-e7lfA',
    appId: '1:1027147869074:ios:b22a888e5e82f88eb1af4b',
    messagingSenderId: '1027147869074',
    projectId: 'nelson-c2230',
    storageBucket: 'nelson-c2230.appspot.com',
    iosClientId: '1027147869074-24huq2hhq4etb59hj7a4ecslv8atr1kn.apps.googleusercontent.com',
    iosBundleId: 'com.nelsonchung.nelsonFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5LfP_5RsYigfO9IxfGjQaO252X-e7lfA',
    appId: '1:1027147869074:ios:f325cabdd55e5e3cb1af4b',
    messagingSenderId: '1027147869074',
    projectId: 'nelson-c2230',
    storageBucket: 'nelson-c2230.appspot.com',
    iosClientId: '1027147869074-b284ei3hk21cr5iebicb0ku4f9nfbtvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.nelsonFirebaseAuth.RunnerTests',
  );
}
